path = "."
abstracts_file = "/home/fjornod/test_nf/aophelpfinder_test/results-eventevent/xml/abstract.xml"
abstracts_type = "xml"
events_file = "/home/fjornod/test_nf/aophelpfinder_test/event-event.txt" #"event_synonym.txt"
events_type = "homemade" #"homemade_synonym"
output_name = "OUTPUTEVENTEVENT"
outputtype = "tsv"
stats_file = "stats.txt"
intro = -1
tm_lemma = False
res_filter = False
context_choice = True
search_mode = "event-event" #"event-event"
